### PR TITLE
Packaging changes

### PR DESCRIPTION
**Pull request by aaronk**
Moved the scripts into the "atacseq" package
setup.py will install the scripts as SAMtoBED and removeChrom

### CODE REVIEW

**Comment by jsh58** [comment]
should add license?

**Comment by aaronk** [comment]
Sure.  I'm a GPL v2 fan.

**Comment by jsh58** [comment]
I like MIT, but since this is under Harvard Informatics... is there a recommended practice?

**Comment by aaronk** [comment]
Ha!  Pretty sure MIT is fine.

ajk

**Comment by aaronk** [comment]
Added.

ajk

**Pull request merged**
